### ISSUE TITLE
Returning dynamic arrays from a function creates a memory leak

### ISSUE THREAD

**Issue by Banbury** [d03n3rfr1tz3/HC-SR04#1]
In C you should never return a dynamic array from a function. C has no garbage collector. So all those arrays you create, will never be deleted. In the loop function of your demo thousands of arrays are created, but never deleted.
If you need to return an array, use return parameters. This way the user is responsible to allocate and delete memory for the array.

**Comment by d03n3rfr1tz3** [comment]
Thank you for your advice. I really appreciate it, as I'm fairly new to C and expected to run into some beginner mistakes.
I'll definitly address this problem asap.

**Comment by d03n3rfr1tz3** [comment]
The memory leak with each measurement is basically fixed with 1e3d0c6e389e7416c231c46c6622f9d8184199d6 now. With the typically syntax that is used in the examples, the library will just reuse a pre-allocated array with each measurement. That way it's still backwards compatible. I also added variants with return parameters for a more advanced handling by the user, as suggested by you.

I might rework this again after a bit more experience with C, but for now it should be enough. Especially the allocation in the begin-function could be improved in the case of multiple calls to it. But I definitly need to get used to all that beforehand.

**Comment by Banbury** [comment]
I would check if the result variable is not NULL, before writing to it.
For the begin function, you could either use a flag when the begin function has already been called. Or you can test if the arrays are not NULL.

**Comment by d03n3rfr1tz3** [comment]
Oh I thought there is much more magic in it than just checking for NULL. Now I feel dumb ;)
