### ISSUE TITLE
Arduino Uno/ATmega328: Only works with echo on pin 2 or 3

### ISSUE THREAD

**Issue by markwalters0** [d03n3rfr1tz3/HC-SR04#2]
Arduino Uno/ATmega328:
Measurement hangs unless pin 2 of 3 are used for the echo pin. Interrupts don't seem to be working on other pins.

**Comment by d03n3rfr1tz3** [comment]
I'm pretty sure that it's caused by _digitalPinToInterrupt_, because I had some problems compiling for some arduino boards. I tried to find a way to separate the code here, but couldn't find an easy way with preprocessor definitions yet, especially because I don't own an arduino myself to test it.

You could try to modify the code locally by removing the function call to _digitalPinToInterrupt_ in line 31 and directly assigning the value. Maybe it works, but I'm seriously just guessing here. Let me know if it makes any difference.

**Comment by d03n3rfr1tz3** [comment]
I have to correct myself, because I realized that the ATmega328 only supports external interrupts on pin 2 and 3. Therefore skipping the _digitalPinToInterrupt_ function should basically do nothing.

To improve compatibility I will recreate what pulseIn does, which is used in most other libraries, but with support of multiple pins.

**Comment by d03n3rfr1tz3** [comment]
https://github.com/d03n3rfr1tz3/HC-SR04/commit/2c23e30aa1b540fded158e668fafa5f786b5f7aa
It took me a while to get back to this, but I added a fallback for pins without interrupt. As mentioned before I recreated pulseIn, but only if a specific pin can not be used as interrupt. So pins with and without interrupt can be mixed.

My tests did not see a noticeable difference in microseconds by using either interrupt or not, but that was mostly tested with an ESP32 with 240Mhz. I might have to substract some delay manually as pulseIn does in the code I found, if it gets noticeable on lower clock speed. The tolerance on my sensors (about 49μs or 84mm with a fixed and completely still sensor) is basically the same as always.
